# defaults
defaults: &defaults
    docker:
      - image: bremerm31/dgswemv2
    environment:
      - DGSWEMV2_ROOT: "/usr/dgswemv2"
      - CI_MPI_CLI: "--allow-run-as-root"

version: 2

jobs:
  checkout_code:
    docker:
      - image: bremerm31/dgswemv2
    working_directory: /usr/dgswemv2
    steps:
      - checkout:
          path: /usr/dgswemv2
      - save_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/dgswemv2
##########################################################################
# Eigen jobs
#this tests if the sfinae to build only SWE support is properly working
  build_dgswemv2_swe_only_eigen:
    working_directory: /usr/dgswemv2/build_eigen
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Building dgswemv2 with eigen---SWE only
          command: |
            cmake --version
            rm -rf /usr/dgswemv2/build_eigen/*
            cmake \
                -DCMAKE_PREFIX_PATH=/usr/install \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_VERBOSE_MAKEFILE=On \
                -DCOMPILER_WARNINGS=On \
                -DUSE_OMPI=On \
                -DUSE_HPX=On \
                /usr/dgswemv2
            make

  build_dgswemv2_eigen:
    working_directory: /usr/dgswemv2/build_eigen
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Building dgswemv2 with eigen
          command: |
            cmake --version
            rm -rf /usr/dgswemv2/build_eigen/*
            cmake \
                -DCMAKE_PREFIX_PATH=/usr/install \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_VERBOSE_MAKEFILE=On \
                -DCOMPILER_WARNINGS=On \
                -DUSE_OMPI=On \
                -DUSE_HPX=On \
                -DRKDG=On \
                /usr/dgswemv2
            make
      - persist_to_workspace:
          root: /usr/dgswemv2
          paths:
            - build_eigen/*
            - test/*

  run_unit_tests_eigen:
    working_directory: /usr/dgswemv2/build_eigen
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /usr/dgswemv2
      - run:
          name: Running unit tests with Eigen
          command: |
            ctest --test-regex unit

  rkdg_run_parallel_correctness_eigen:
    working_directory: /usr/dgswemv2/build_eigen
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /usr/dgswemv2
      - run:
          no_output_timeout: 60m
          name: RKDG Parallel Manufactured Solution with Eigen
          command: |
            /usr/dgswemv2/scripts/correctness/test_swe_parallel_correctness.sh rkdg_swe build_eigen

  rkdg_run_parallel_weirs_eigen:
    working_directory: /usr/dgswemv2/build_eigen
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /usr/dgswemv2
      - run:
          no_output_timeout: 60m
          name: RKDG Parallel Weirs with Eigen
          command: |
            /usr/dgswemv2/scripts/correctness/test_rkdg_parallel_weirs.sh build_eigen

##########################################################################
# Blaze jobs
  build_dgswemv2_swe_only_blaze:
    working_directory: /usr/dgswemv2/build_blaze
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Building dgswemv2 with blaze---SWE only
          command: |
            cmake --version
            rm -rf /usr/dgswemv2/build_blaze/*
            cmake \
                -DCMAKE_PREFIX_PATH=/usr/install \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_VERBOSE_MAKEFILE=On \
                -DCOMPILER_WARNINGS=On \
                -DUSE_OMPI=On \
                -DUSE_HPX=On \
                -DUSE_BLAZE=On \
                /usr/dgswemv2
            make

  build_dgswemv2_blaze:
    working_directory: /usr/dgswemv2/build_blaze
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Building dgswemv2 with blaze
          command: |
            cmake --version
            rm -rf /usr/dgswemv2/build_blaze/*
            cmake \
                -DCMAKE_PREFIX_PATH=/usr/install \
                -DCMAKE_BUILD_TYPE=Debug \
                -DSET_VERBOSE=On \
                -DCMAKE_VERBOSE_MAKEFILE=On \
                -DUSE_OMPI=On \
                -DUSE_HPX=On \
                -DRKDG=On \
                -DUSE_BLAZE=On \
                /usr/dgswemv2
            make
      - persist_to_workspace:
          root: /usr/dgswemv2
          paths:
            - build_blaze/*
            - test/*

  run_unit_tests_blaze:
    working_directory: /usr/dgswemv2/build_blaze
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /usr/dgswemv2
      - run:
          name: Running unit tests with Blaze
          command: |
            ctest --test-regex unit

  rkdg_run_parallel_correctness_blaze:
    working_directory: /usr/dgswemv2/build_blaze
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /usr/dgswemv2
      - run:
          no_output_timeout: 60m
          name: RKDG Parallel Manufactured Solution with Blaze
          command: |
            /usr/dgswemv2/scripts/correctness/test_swe_parallel_correctness.sh rkdg_swe build_blaze

  rkdg_run_parallel_weirs_blaze:
    working_directory: /usr/dgswemv2/build_blaze
    <<: *defaults
    steps:
      - restore_cache:
          key: v2-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /usr/dgswemv2
      - run:
          no_output_timeout: 60m
          name: RKDG Parallel Weirs with Blaze
          command: |
            /usr/dgswemv2/scripts/correctness/test_rkdg_parallel_weirs.sh build_blaze

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - build_dgswemv2_swe_only_eigen:
          requires:
            - checkout_code
      - build_dgswemv2_eigen:
          requires:
            - checkout_code
      - run_unit_tests_eigen:
          requires:
            - build_dgswemv2_eigen
      - rkdg_run_parallel_correctness_eigen:
          requires:
            - build_dgswemv2_eigen
      - rkdg_run_parallel_weirs_eigen:
          requires:
            - build_dgswemv2_eigen
      - build_dgswemv2_swe_only_blaze:
          requires:
            - checkout_code
      - build_dgswemv2_blaze:
          requires:
            - checkout_code
      - run_unit_tests_blaze:
          requires:
            - build_dgswemv2_blaze
