version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.11
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - dgswemv2-dependencies

#      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo add-apt-repository -y ppa:ppsspp/cmake
#      - run: sudo apt-get update
#      - run: sudo apt-get install -y gcc-6 g++-6 cmake libgoogle-perftools-dev libhwloc-dev mpi-default-dev openmpi-bin
#      - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20
#      - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20
#      - run: ./scripts/circleci/set-up-dependencies.sh
#      - run: sudo apt-get install python-dev
#      - run: pip install numpy
#      - run: scripts/circleci/build.sh

#      - save_cache:
#          key: dgswemv2-dependencies
#          paths:
#            - "/home/ubuntu/yaml-cpp"
#            - "/home/ubuntu/hpx"
#            - "/home/ubuntu/build"
#            - "/home/ubuntu/install"

  test:
    docker:
      - image: circleci/python:2.7.11
    steps:
      - run: scripts/circleci/test.sh
      - run: scripts/correctness/test_parallel_correctness.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test