defaults: &defaults
    working_directory: /usr/dgswemv2/build
    docker:
      - image: bremerm31/dgswemv2

version: 2

jobs:
  checkout_code:
    docker:
      - image: bremerm31/dgswemv2
    working_directory: /usr/dgswemv2/build
    steps:
      - checkout:
          path: /usr/dgswemv2
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/dgswemv2